### ISSUE TITLE
The web dev blog doesn't  works

### ISSUE THREAD

**Issue by AlphaTechnolog** [alxsmora1/alxsmora1#5]
I want to go to your blog (The web dev), and an error (Server not found) on firefox was happened
Screenshot: 
![Captura de pantalla de 2021-05-09 13-56-57](https://user-images.githubusercontent.com/54639968/117582126-73f32c00-b0ce-11eb-91c7-ca4a57e5601a.png)

**Comment by alxsmora1** [comment]
Thank you, the blog is offline because I'm working on migrating this to Netlify. When the migration has ended, I will add the link to my readme.

**Comment by AlphaTechnolog** [comment]
Oh ok
